### ISSUE TITLE
Update for 1.10.0-RC

### ISSUE THREAD

**Issue by awoods** [vivo-community/vivo-vagrant#36]
It would be good if the `master` branch would pull the latest 1.10.0 release candidate.

**Comment by delsborg** [comment]
I would like to use the format that I setup with the gui dev branch for Vagrant. This pulls from the  https://github.com/vivo-community/vivo-project-template repo. So first thing is we need a template that pulls from 1.10.0-RC. Is there a way to link this issue to the vivo-project-template repo?

**Comment by mconlon17** [comment]
Resolved by https://github.com/vivo-community/vivo-vagrant/commit/803da0430bb327df637a11276443390f5d52096a
