### ISSUE TITLE
create v1.10 branch

### ISSUE THREAD

**Issue by kgeis** [vivo-community/vivo-vagrant#40]
I'd like to submit PRs for the 1.10 final release. It doesn't make sense to target those to the rel-1.10.0-RC-1 branch. There should be a v1.10 branch to follow the other v1.x named branches.

**Comment by gneissone** [comment]
@awoods previous versions have lived in their own branches. The 1.10 release is currently in master. Assuming we want to keep the pattern, can you create a new 1.10 branch from master? I don't have admin permissions in this repo.

**Comment by roflinn** [comment]
@gneissone It is there: https://github.com/vivo-community/vivo-vagrant/tree/v1.10
